### ISSUE TITLE
大佬你好！！！

### ISSUE THREAD

**Issue by lousiming** [thswodnjs3/CSTA#3]
可不可以加个微信大佬，想学习下

**Comment by thswodnjs3** [comment]
Did you mean "WeChat"? I'm not using that program. Sorry about it.

**Comment by lousiming** [comment]
What social media apps do you usually use? I would like to learn from you! My English is not very good, and I apologize for that.

**Comment by thswodnjs3** [comment]
You can ask me questions using Github issues.

You can also ask me using emails.
(   31z522x4@skku.edu   )
